"""Cookie 文件存储：原始字符串 + Netscape 格式转换（convert_cookie.py 内聚于此）。"""
from pathlib import Path


class CookieStore:
    def __init__(self, raw_file: Path, netscape_file: Path, legacy_raw: Path | None = None):
        self._raw_file = raw_file
        self._netscape_file = netscape_file
        self._legacy_raw = legacy_raw  # 兼容旧版根目录 cookie 文件（只读回退）

    # ---- 读取 ----

    def has_cookie(self) -> bool:
        return self._raw_file.exists() or bool(self._legacy_raw and self._legacy_raw.exists())

    def read_raw(self) -> str | None:
        for f in (self._raw_file, self._legacy_raw):
            if f and f.exists():
                content = f.read_text("utf-8", errors="ignore").strip()
                if content:
                    return content
        return None

    def read_netscape(self) -> Path | None:
        if self._netscape_file.exists():
            return self._netscape_file
        if self.has_cookie():
            raw = self.read_raw()
            if raw:
                self.save_raw(raw)
                return self._netscape_file
        return None

    # ---- 写入 ----

    def save_raw(self, cookie: str) -> Path:
        cookie = cookie.strip()
        if not cookie:
            raise ValueError("Cookie 为空")
        self._raw_file.parent.mkdir(parents=True, exist_ok=True)
        self._raw_file.write_text(cookie, encoding="utf-8")
        return self.to_netscape()

    def to_netscape(self) -> Path:
        """按 yt-dlp 支持的 Netscape 格式转换 .bilibili.com 全站 Cookie。"""
        raw = self.read_raw()
        if not raw:
            raise ValueError("无原始 Cookie 可转换")
        lines = [
            "# Netscape HTTP Cookie File",
            "# https://curl.haxx.se/rfc/cookie_spec.html",
            "# Generated by BiliDownloader. Do not edit!",
            "",
        ]
        for item in raw.split(";"):
            item = item.strip()
            if "=" not in item:
                continue
            name, value = item.split("=", 1)
            name, value = name.strip(), value.strip()
            if not name:
                continue
            # domain    flag    path    secure    expiry    name    value
            lines.append(f".bilibili.com\tTRUE\t/\tFALSE\t0\t{name}\t{value}")
        self._netscape_file.parent.mkdir(parents=True, exist_ok=True)
        self._netscape_file.write_text("\n".join(lines) + "\n", encoding="utf-8")
        return self._netscape_file